export const CREATE_EMPLOYEE = 'employees/CREATE_EMPLOYEE'
export const CREATE_EMPLOYEE_COMPLETE = 'employees/CREATE_EMPLOYEE_COMPLETE'
export const CREATE_EMPLOYEE_FAILED = 'employees/CREATE_EMPLOYEE_FAILED'
export const CLEAR_EMPLOYEE = 'employees/CLEAR_EMPLOYEE'