export const FETCH_EMPLOYEE = 'employees/FETCH_EMPLOYEE'
export const FETCH_EMPLOYEE_COMPLETE = 'employees/FETCH_EMPLOYEE_COMPLETE'
export const FETCH_EMPLOYEE_FAILED = 'employees/FETCH_EMPLOYEE_FAILED'
export const CLEAR_EMPLOYEE = 'employees/CLEAR_EMPLOYEE'